# version属性は削除
services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    restart: always
    volumes:
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    # portsセクションは完全に削除
    depends_on:
      - redis
    command: gunicorn runners_insight.wsgi:application --bind 0.0.0.0:8000

  celery:
    build: ./backend
    restart: always
    volumes:
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: celery -A runners_insight worker --loglevel=info

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - media_volume:/usr/share/nginx/html/media

volumes:
  redis_data:
  media_volume:
